# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'Hu-Food' do

  #firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  
  pod 'Reusable', '4.0.5'
  pod 'Then', '2.4'
  
  # Networking
  pod 'Alamofire', '~> 4.8.1'
  
  # Mapping
  pod 'AlamofireObjectMapper', '~> 5.2.0'
  
  # Convention
  pod 'SwiftLint', '~> 0.31.0'
  
  # Database
  pod 'Realm', '~> 3.13.1'
  
  #  Image
  pod 'Kingfisher', '4.10.1'

end
